export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_CHANGE_USER = 'LOGIN_CHANGE_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
export const LOGIN_FORM_SHOW = 'LOGIN_FORM_SHOW';

export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
